### ISSUE TITLE
Login wirft Fehlermeldung

### ISSUE THREAD

**Issue by jommbee** [terminal42/contao-password-validation#1]
Hallo,
nach Installtion der Erweiterung in einer Contao 4.4.43, wird beim Loginversuch ins Backend (als Admin) eine Fehlermeldung ausgegeben. Im Log steht:

`[2019-09-17 11:25:47] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'UPDATE tl_user SET `id`='3', `tstamp`='1568719032', `username`='XXXX', `name`='XXXX', `email`='XXXX', `language`='de', `backendTheme`='flexible', `limitWidth`='', `uploader`='', `showHelp`='1', `thumbnails`='1', `useRTE`='1', `useCE`='1', `password`='XXXX', `pwChange`='', `admin`='1', `groups`=NULL, `inherit`='', `modules`=NULL, `themes`=NULL, `pagemounts`='a:0:{}', `alpty`=NULL, `filemounts`='a:0:{}', `fop`=NULL, `imageSizes`=NULL, `forms`=NULL, `formp`=NULL, `amg`=NULL, `disable`='', `start`='', `stop`='', `session`='a:2:{s:23:\\\"tl_article_tl_page_tree\\\";a:1:{i:1;i:0;}s:12:\\\"tl_page_tree\\\";a:1:{i:1;i:0;}}', `dateAdded`='1568719032', `lastLogin`='1568719387', `currentLogin`=1568719547, `loginCount`=NULL, `locked`='0', `calendars`=NULL, `calendarp`=NULL, `calendarfeeds`=NULL, `calendarfeedp`=NULL, `faqs`=NULL, `faqp`=NULL, `news`=NULL, `newp`=NULL, `newsfeeds`=NULL, `newsfeedp`=NULL, `newsletters`=NULL, `newsletterp`=NULL, `filterformp`=NULL, `filterform`=NULL, `catalogp`=NULL, `catalog`=NULL, `maeEventCatDefault`=NULL, `maeEventCat`='', `calendareventstagsrelationp`=NULL, `calendareventstagsp`=NULL WHERE id='3'':\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'loginCount' cannot be null at C:\\laragon\\www\\templateboosting\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:123, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'loginCount' cannot be null at C:\\laragon\\www\\templateboosting\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:109, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'loginCount' cannot be null at C:\\laragon\\www\\templateboosting\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:107)"} []`

Auf der Website selber wird zuerst die Standrd Fehlermeldung von Contao ausgegeben. Bei Reload (erneute Übermittlung bestätigen) der Seite zeigt sich aber die Fehlermeldung die auch in der Log Datei steht.

Entferne ich in diesem Zustand den Teil Login aus dem URL (/contao/login) komme ich angemeldet ins Backend.

**Comment by richardhj** [comment]
Danke fürs melden! Ist gelöst.
