### ISSUE TITLE
with the extension a login is no longer possible

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-password-validation#6]
If the extension is installed and you create a new PW in the BE, you cannot log in with it.

Contao 4.9.5

related with #3

**Comment by Toflar** [comment]
@richardhj is this a duplicate of #3 aka going to be fixed in Contao core? If so, please close this :) Thx

**Comment by richardhj** [comment]
I found an incompatibility when using PHP>=7.4.

> 7.4.0 | The values of the password algo IDs (PASSWORD_BCRYPT, PASSWORD_ARGON2I, PASSWORD_ARGON2ID and PASSWORD_DEFAULT) are now strings. Previously, they have been integers.

Fixed in 0d40143e8839c213b1b2c35bb0a68cfc47eb99b9.

**Comment by zonky2** [comment]
O.K. - I had PHP 7.2
